### ISSUE TITLE
Czech UI translation support

### ISSUE THREAD

**Issue by matysek** [icefields/Power-Ampache-2#106]
Hello, thanks for the awesome app. What is the best way to be able add UI translation for the app?

- I'd like to create it for my native language.
- It seems like the best way is to translate this file: https://github.com/icefields/Power-Ampache-2/blob/main/app/src/main/res/values/strings.xml
- Is it supported by default?
- Do you have any link to any docs how to do it?

**Comment by icefields** [comment]
hello, thanks for reaching out. 
Editing that file is the best way to contribute to translations right now.
I will automate translation contributions in the future, but for now you have a few of options.
- If you're an Android developer just create the resource directories and open a PR.
- If you're not familiar with Android development and don't know how to create translation resources, but you are able to edit XML files: you can just grab that file you linked in the initial comment, edit it and send it back to me. I'll review it and will include it in the app in the next release.
Example (italian translation):
```
<resources>
...
    <string name="albumDetailScreen_infoSection_year">Anno</string>
    <string name="albumDetailScreen_infoSection_songs">Canzoni</string>
    <string name="albumDetailScreen_infoSection_time">Tempo Totale</string>
    <string name="playlistDetailScreen_infoSection_avgRating">Voto Medio</string>
    <string name="playlistItem_songCount">%s Canzoni</string>
    <string name="topBar_search_hint">Search Canzoni, Album, Artisti, Playlist</string>
...
```
- If you're not familiar with Android development and also not sure how to edit xml files, just send me a text document with the translations and I will take care of it.

Thanks.

**Comment by matysek** [comment]
Thanks for response, I created this one: https://github.com/icefields/Power-Ampache-2/pull/109

**Comment by icefields** [comment]
> Thanks for response, I created this one: #109
Fantastic, thanks!
I got some conflicts with my work because I was reorganizing strings to have all the translatable ones in one place and all the config ones elsewhere.
Anyway, I will fix the conflicts and have the translations ready for next release.

**Comment by icefields** [comment]
Your translations will be available with today's release. 
There's a few strings in the app that are still hardcoded in English, I will add them to the string.xml file as I find them. Can I bother you to translate those as well?
Thanks
