### ISSUE TITLE
[FEATURE?] Toggle favorite for artists and tracks

### ISSUE THREAD

**Issue by JoeDat** [icefields/Power-Ampache-2#128]
Running v1.00-59

Marked with a ? because I'm unsure if I'm just not seeing how to do it if it's already an option.  I can see tracks and artists marked with a heart in the UI if tagged as a favorite previously, but do not see a way to toggle on/off in the app.  UI appears to allow toggle for albums only.

**Comment by icefields** [comment]
hello @JoeDat here's some screenshots where I highlight where the like and the rating toggles are for each screen/item : 
# SONG
![image](https://github.com/icefields/Power-Ampache-2/assets/149625124/3ddf5e2e-d18c-45a8-8f37-9fd8bd731332)

# PLAYLIST
![image](https://github.com/icefields/Power-Ampache-2/assets/149625124/efc5e64f-f9e5-4013-a23f-46136cb11aab)

# ALBUM 
![image](https://github.com/icefields/Power-Ampache-2/assets/149625124/ff079960-a0cc-4a7b-aab7-23b76ef1d670)

Artist does not have those toggles/buttons in the app.

**Comment by icefields** [comment]
yes, the option for artist can be enabled. Since more than one person asked for it, I will implement it in the next version.

**Comment by JoeDat** [comment]
@icefields  Works great, thanks!
