### ISSUE TITLE
Cannot connect to Navidrome Server

### ISSUE THREAD

**Issue by OofYeetMcGee** [icefields/Power-Ampache-2#131]
Hello, 

I can't seem to connect to my Navidrome server. The only error is "Cannot connect to your server". I tried connecting to the server with another subsonic client and it worked.

Thanks!

**Comment by icefields** [comment]
hello,
Navidrome seems to be a Subsonic backend, I cheched the API specs and the calls don't seem to follow the Ampache protocol. Please use Ampache or an Ampache compatible backend with Power Ampache 2.

**Comment by OofYeetMcGee** [comment]
Okay thank you
