### ISSUE TITLE
No login possoble to nextcloud music v2.0.0

### ISSUE THREAD

**Issue by Kenarso** [icefields/Power-Ampache-2#141]
I use ampache server nextcloud music in version v2.0.0
I use the whole thing on my own server with a Let's encrypt signed certificate. 
I cannot log in to the server.
I get the message to use the Misic version v2.0.0 or higher, which I have. So what can I do?

**Comment by icefields** [comment]
hello,
is it possible for you to create a test account for me on your nextcloud server? So I can debug the issue from my IDE. This would be the easiest way for me to help you.
I also need to know which version of Power Ampache 2 are you using, thanks.

**Comment by Kenarso** [comment]
Yes, this is possible. Jave you a E-Mail address for me?
I ise the newest Version from  F-Droid 1.00-62-fdroid.

**Comment by icefields** [comment]
Yeah for sure, some of the contacts methods are in the readme:
email: arctic.icefields @ slmails . com
telegram: https://t.me/PowerAmpache2
mastodon: https://floss.social/@powerampache
