### ISSUE TITLE
Enable token login

### ISSUE THREAD

**Issue by icefields** [icefields/Power-Ampache-2#26]
When logging in with auth token there is no way to retrieve the username, this is causing crashes and bugs on all the features that require a username to function (ie. playlist editing, I need to know the playlist belongs to the user to allow editing).

I removed token login option for now. But token login must be implemented. Users logging in with a token won't be able to edit playlists and all the other features that depend on the username will be disabled.

**Comment by usox** [comment]
Hi

Since it is not so easy to change existing API methods in ampache: Would it be a solution to have an API method that can be used to retrieve private information about the "current user" (i.e. the one to whom the current login information/token belongs)? This would include the username, for example.

**Comment by icefields** [comment]
hey @usox ,
yes that would work, right now I'm retrieving the user object [with this method](https://ampache.org/api/api-json-methods#user), if a new method is implemented, that returns the same object, my job would be as easy as changing an endpoint in the code.

**Comment by usox** [comment]
> if a new method is implemented, that returns the same object, my job would be as easy as changing an endpoint in the code.

I'll take a look at it. Shouldn't be a big deal.

**Comment by usox** [comment]
ampache/ampache#3807

**Comment by fufroma** [comment]
I think it's fixed in `PowerAmpache2-1.00-60-free`

Related to #120
