### ISSUE TITLE
404 Timeout While Minimized

### ISSUE THREAD

**Issue by BlueNalgene** [icefields/Power-Ampache-2#54]
I received an error after opening Power Ampache 2 from a minimized state.  Error message:

```
HTTP 404 { "exception" : "failed to connect to <website>/<my public IP> (port 443) from /<my internal ip> (port 46430) after 20000ms: isConnected failed: ETIMEDOUT (Connection timed out)" }
```

The app seems to be functioning when I keep poking things.  It may not be correctly pulling info while not in use.

Edit: I forgot my vitals.

Power Ampache 2 version: v0.19-beta

Device: OnePlus 7T
Processor: Qualcomm Snapdragon 855Plus Octa-core
Model: HD1905
Android version: 12 (security update Dec. 5, 2022)
Build version: HD1905_11_F.22
Baseband version: Q_V1:P14,Q_V1_P14
Kernel: 4.14.180-perf+

**Comment by icefields** [comment]
thanks for the report, I'm familiar with that error, your server was either temporarely unreachable or the was a token-refresh happening and some previous pending call failed, or the app was doing too much work on that thread and timed out to retry in xx seconds.
The app is a bit verbose right now with errors. If everything is working fine afterwards it means that the connection-retry was successfull. But I will look into it anyway.

**Comment by BlueNalgene** [comment]
Awesome.  I'm a big fan of this app so far and I want to help it succeed.  The release notes say "Please report any bug," so I'm trying to do my part to break it.

Closing since this error message was not relevant.
